Bevy 0.14
zaycev/bevy-magic-light-2d pull request #59
Opened 2024-07-08 12:48 UTC by csandven

2024-07-10 06:13 UTC, cyclopanic commented
![ss](https://github.com/zaycev/bevy-magic-light-2d/assets/174174981/dca0fbf5-11f9-4fc2-832f-b91f2a7c8f60)
not sure why the tilemap example seems to not render properly

2024-07-15 21:02 UTC, Rezan7CC requested changes
I like the formatting changes but would it be possible to make those separately from the Bevy upgrade?

2024-07-18 15:29 UTC, zaycev commented
@cyclopanic Not a blocker for the review, but I agree with @Rezan7CC. Do you think it's possible to submit formatting changes as a separate PR?

2024-07-18 19:03 UTC, zaycev commented on examples/krypta.rs
> +        .insert_resource(ClearColor(Color::srgba_u8(0, 0, 0, 0)))
Wonder why we should use a different color space?

2024-07-23 10:30 UTC, tigerplush commented
Color space has changed according to https://bevyengine.org/learn/migration-guides/0-13-to-0-14/#overhaul-color

2024-07-23 11:09 UTC, tigerplush requested changes
Please change magic number

2024-07-23 11:09 UTC, tigerplush commented on src/gi/compositing.rs
> +    let layer = RenderLayers::layer(31);
@csandven what is this magic number?

2024-08-03 16:17 UTC, closed without merging